// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjhekslujbhmqsbjhehe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqaGVrc2x1amJobXFzYmpoZWhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDI1NjEsImV4cCI6MjA2NTUxODU2MX0.tAWnY9KhWcd_mzi5lxwW848eNE3LN3W8ULOLLJMXxnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);